kind: Pod
apiVersion: v1
metadata:
  name: sample02
spec:
  containers:
    - name: sample
      image: centos:7
      command: ["sleep", "10000"]
      envFrom:
        - configMapRef:
            name: sample

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sample
data:
  URL: google.com
  KEY: abc123
