kind: Pod
apiVersion: v1
metadata:
  name: sample02
spec:
  containers:
    - name: sample1
      image: nginx
      livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
