kind: Pod
apiVersion: v1
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/frontend:3.0.0

---
kind: Pod
apiVersion: v1
metadata:
  name: catalogue
spec:
  containers:
    - name: catalogue
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/catalogue:3.0.0

---
kind: Pod
apiVersion: v1
metadata:
  name: cart
spec:
  containers:
    - name: cart
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/cart:3.0.0

---
kind: Pod
apiVersion: v1
metadata:
  name: user
spec:
  containers:
    - name: user
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/user:3.0.0

---
kind: Pod
apiVersion: v1
metadata:
  name: shipping
spec:
  containers:
    - name: shipping
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/shipping:3.0.0

---
kind: Pod
apiVersion: v1
metadata:
  name: payment
spec:
  containers:
    - name: payment
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/payment:3.0.0

