kind: Pod
apiVersion: v1
metadata:
  name: frontend
  labels:
    COMPONENT: frontend
spec:
  containers:
    - name: frontend
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/frontend:3.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-np
spec:
  type: NodePort
  selector:
    COMPONENT: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
---
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  type: LoadBalancer
  selector:
    COMPONENT: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: catalogue
  labels:
    COMPONENT: catalogue
spec:
  containers:
    - name: catalogue
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/catalogue:3.0.2
      env:
        - name: DOCUMENTDB
          value: "true"
        - name: MONGO_URL
          value: "mongodb://admin1:RoboShop123@prod-docdb.cluster-cbvsbeoyxek4.us-east-1.docdb.amazonaws.com:27017/catalogue?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"


---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    COMPONENT: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: cart
  labels:
    COMPONENT: cart
spec:
  containers:
    - name: cart
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/cart:3.0.0
      env:
        - name: REDIS_HOST
          value: prod-redis.nud0cy.0001.use1.cache.amazonaws.com
        - name: CATALOGUE_HOST
          value: catalogue
        - name: CATALOGUE_PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    COMPONENT: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
kind: Pod
apiVersion: v1
metadata:
  name: user
  labels:
    COMPONENT: user
spec:
  containers:
    - name: user
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/user:3.0.1
      env:
        - name: DOCUMENTDB
          value: "true"
        - name: MONGO_URL
          value: "mongodb://admin1:RoboShop123@prod-docdb.cluster-cbvsbeoyxek4.us-east-1.docdb.amazonaws.com:27017/users?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
        - name: REDIS_HOST
          value: prod-redis.nud0cy.0001.use1.cache.amazonaws.com

---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    COMPONENT: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
kind: Pod
apiVersion: v1
metadata:
  name: shipping
  labels:
    COMPONENT: shipping
spec:
  containers:
    - name: shipping
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/shipping:3.0.0
      env:
        - name: CART_ENDPOINT
          value: cart:8080
        - name: DB_HOST
          value: prod-rds.cluster-cbvsbeoyxek4.us-east-1.rds.amazonaws.com

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    COMPONENT: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: payment
  labels:
    COMPONENT: payment
spec:
  containers:
    - name: payment
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/payment:3.0.2

---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    COMPONENT: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
